---
- name: install firewalld
  yum: 
    name: firewalld
    state: present

- name: disable firewall
  service: 
    name: firewalld
    state: stopped

- name:  remove firewall init
  shell: systemctl disable firewalld
