---
- name: disable firewall
  service: 
    name: firewalld
    state: stopped

- name:  remove firewall init
  shell: systemctl disable firewalld

- name: close selinux
  shell: setenforce 0

- name: disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'