- name: copy rpm
  copy: src={{ item }} dest=/tmp/
  with_items: 
    - "{{ logrotate }}"
    - "{{ zabbix }}"

- name: install rpm
  shell: rpm -i {{ item }}
  with_items:
    - /tmp/"{{ logrotate }}"
    - /tmp/"{{ zabbix }}"

- name: copy zabbix config
  template: src="zabbix_agentd.conf" dest="/etc/zabbix/zabbix_agentd.conf"