---
- name: change root password
  shell: echo P@ssw0rd | passwd root --stdin

- name: add DNS
  shell: echo 'nameserver  114.114.114.114' >> /etc/resolv.conf

- name: modify ssh.config
  lineinfile: 
    path: /etc/ssh/ssh_config
    regexp: '^(\#)[\s\S]*StrictHostKeyChecking'
    line: 'StrictHostKeyChecking no'











