---
- name: mkdir rpm dir
  shell: mkdir -p /tmp/rpm/

- name: copy all rpm
  copy: src=rpm.tar dest=/tmp/

- name: unzip rpm.tar
  shell: tar -xvf /tmp/rpm.tar -C /tmp/rpm

- name: rpm install
  shell: rpm -ivh /tmp/rpm/*.rpm

- name: zabbix for httpd conf
  template: src=zabbix.conf dest=/etc/httpd/conf.d/zabbix.conf
  notify: 
    - restart httpd

- name: copy mariadb rpm tar
  copy: src=mariadb.tar.gz dest=/tmp/

- name: unzip tar.gz
  shell: tar -zxvf /tmp/mariadb.tar.gz -C /tmp/mariadb

- name: install mariadb rpm
  shell: rpm -ivh /tmp/mariadb/*.rpm

- name: startup mariadb
  

- name: unzip create.sql.gz
  shell: gzip -d /usr/share/doc/zabbix-server-mysql-3.4.4/create.sql.gz

- name: copy script to server
  copy: src=setup_mysql.sh dest=/tmp/

- name: run shell script
  shell: bash /tmp/setup_mysql.sh




